### ISSUE TITLE
findind new rotor permutation

### ISSUE THREAD

**Issue by jeromew** [the-lambda-way/bruteforce-enigma#15]
Hello,

I am trying to find/modify a tool to crack the old crypt/enigma command line tool that uses a trivialized enigma machine.
Basically, it is a one rotor machine with an alphabet of size 256 (256 bytes).
The algorithm is along the line of cypherChar = permutation(plainChar + charPos) - charPos

do you think bruteforce-enigma could be a good starting point ? does it search for unknown rotor permutations ?

the enigma command has 2 levels of complexity
 - it maps a key to a rotor permutation
 - it then uses that permutation to crypt/decrypt the message

for more references :
 - https://en.wikipedia.org/wiki/Crypt_(Unix)
 - https://github.com/freebsd/freebsd-src/blob/main/usr.bin/enigma/enigma.c

I also saw https://github.com/ffraenz/bomm and https://cdn.ciphereditor.com/archive/2023/breaking-enigma-ciphertext-in-2023.pdf that might be of interest to you

**Comment by the-lambda-way** [comment]
Hi there! This tool does find rotor permutations, and the size of the results can be increased to find additional / all of the equivalent permutations (i.e. ring positions). I'll look into, today, the resources you provided and give you my advice . I suspect this code is overly-complicated for your use case, but if you only care about getting something working, that shouldn't matter.

**Comment by the-lambda-way** [comment]
Ok, I read up on the crypt/enigma command. I didn't get at first you meant the rotor itself is a random alphabet. My program is optimized for *permuting* rotor and ring positions, as well as threading multiple rotor order combinations. I don't think it will offer much performance benefit for rapidly testing arbitrary rotor definitions. Additionally, the double stepping mechanism might be incompatible with the crypt implementation. My guess is a hill-climbing algorithm is the way to go for breaking crypt. Perhaps some peculiarity of the crypt design would open up some other shortcuts too.

But this is an interesting project. I'd be happy to consult with you on designing a fast algorithm to crack it. Maybe I'll get to making one myself one day as well.

Thanks for the link to the thesis. It's on my reading list. I also came across this existing program to break crypt with only the ciphertext, if you haven't seen it yet. https://www.mathstat.dal.ca/~selinger/unixcrypt-breaker/

**Comment by jeromew** [comment]
Thank you for your answer,

I had seen unixcrypt-breaker but to use it you need to have a corpus of text that has the same letter statistics as the plain text you are trying to decode. I am not sure there is really a way out of this.

I just have one cyphertext to decode (a short one of 39 chars) so I don't really know if I can do it without the key or without good statistics but I will look into hill climbing.

If you try it as an interesting exercise, I can also point you to an interesting "historical" article about the cryptanalysis of `crypt` 
- [File Security and the UNIX System Crypt Command](http://squoze.net/UNIX/bltj/06771913.pdf)
