### ISSUE TITLE
build error on M1 Apple Silicon

### ISSUE THREAD

**Issue by Smiril** [the-lambda-way/bruteforce-enigma#5]
may is this machine specific or code specific?

`clang: warning: treating 'c-header' input as 'c++-header' when in C++ mode, this behavior is deprecated [-Wdeprecated]
clang: warning: treating 'c-header' input as 'c++-header' when in C++ mode, this behavior is deprecated [-Wdeprecated]
clang: warning: treating 'c-header' input as 'c++-header' when in C++ mode, this behavior is deprecated [-Wdeprecated]
clang: warning: treating 'c-header' input as 'c++-header' when in C++ mode, this behavior is deprecated [-Wdeprecated]
Building build/bruteforce.o .../bin/sh: -f: command not found

real	0m0.002s
user	0m0.000s
sys	0m0.001s
make: *** [build/bruteforce.o] Error 127`

**Comment by the-lambda-way** [comment]
The problem was that Macs use zsh instead of bash, and zsh's time command doesn't take any flags. As far as I know, Macs share some of the linux directory structure, so I think this will work.
