### ISSUE TITLE
Bruteforcing/cracking unknown rotors with rotors - Kriegsmarine model

### ISSUE THREAD

**Issue by Alexthemediocre** [the-lambda-way/bruteforce-enigma#9]
It should be made more clear in the README that to solve for unknown rotors including VI, VII, and VIII, `kriegsmarine_model` should be passed to smart_decipher/bruteforce_decipher instead of `m3_model`. I was under the impression that `m3_model` would have contained the extra rotors, based on some other tools.

**Comment by the-lambda-way** [comment]
Good point. I am thinking about whether to make Kriegsmarine the default M3 in the future.

I added some comments to the README in commit c126b34.
